spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://188.120.229.201:5433/hammi
    username: hammi
    password: hammi
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855

module:
  user:
    service-url: http://user-service:8082

server:
  port: 8083